# Generated by Django 4.1.3 on 2023-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('Id_no', models.CharField(max_length=10)),
            ],
        ),
    ]
