# Generated by Django 4.1.3 on 2023-04-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0002_dialer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialer',
            name='Id_no',
        ),
    ]
